version: '3.3'

services:
 web:
  build:
   context: .
  ports:
  - 8080:8080
  volumes:
  - ./:/app

 mysqldb:
  image: mysql
  ports:
  - 3306
  environment:
  - MYSQL_ROOT_PASSWORD=p@ssword1
  volumes:
  - mysql:/var/lib/mysql
  - mysql_config:/etc/mysql

volumes:
  mysql:
  mysql_config: